<?php
declare(strict_types=1);
define('B24_WEBHOOK_URL', 'https://tris.bitrix24.by/rest/77/hjhrikll05vwf9sq/');
define('DATA_ROOT', '/var/www/Tris-Servis2026/data');
define('APP_URL',   '');
define('APP_PATH',  '/var/www/Tris-Servis2026');
define('B24_TOKENS_FILE',     DATA_ROOT . '/b24-tokens.php');
define('SETTINGS_FILE',       DATA_ROOT . '/settings.php');
define('SESSIONS_FILE',       DATA_ROOT . '/sessions.php');
define('STATE_FILE',          DATA_ROOT . '/state.php');
define('LAST_SYNC_FILE',      DATA_ROOT . '/last_sync.php');
define('DEAL_CELLS_FILE',     DATA_ROOT . '/deal_cells.php');
define('DEAL_INFO_FILE',      DATA_ROOT . '/deal_info.php');
define('RESOURCE_NAMES_FILE', DATA_ROOT . '/resource_names.php');
define('SHEETS_ID',       '1jjBjuwvxChxmk0L5_Rk9Sr4it9v47AZCCbaHXEyMhr4');
define('SHEETS_SHEET',    'Лист1');
define('GOOGLE_SA_FILE',  DATA_ROOT . '/google-sa-key.php');
define('GOOGLE_TOK_FILE', DATA_ROOT . '/google_token.php');
define('B24_BOOKING_FIELDS', []);
define('TECH_COLUMNS', []);